name: "Deploy [AJUSTAR: nome da aplicacao]"

on:
  push:
    branches: [dev, hml, main]
  workflow_dispatch: {}

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    uses: AURA-ENG-DEVOPS/.github/.github/workflows/deploy-docker-compose.yml@main
    with:
      environment: dev
      runner_label: runner-devhml
      service: "[AJUSTAR: nome-do-servico]-dev"
      # host_dirs: |
      #   /srv/dev/[AJUSTAR: nome-do-servico]/data

  deploy-hml:
    if: github.ref == 'refs/heads/hml'
    uses: AURA-ENG-DEVOPS/.github/.github/workflows/deploy-docker-compose.yml@main
    with:
      environment: hml
      runner_label: runner-devhml
      service: "[AJUSTAR: nome-do-servico]-hml"
      # host_dirs: |
      #   /srv/hml/[AJUSTAR: nome-do-servico]/data

  deploy-prd:
    if: github.ref == 'refs/heads/main'
    uses: AURA-ENG-DEVOPS/.github/.github/workflows/deploy-docker-compose.yml@main
    with:
      environment: prd
      runner_label: runner-prd
      service: "[AJUSTAR: nome-do-servico]-prd"
      # host_dirs: |
      #   /srv/prd/[AJUSTAR: nome-do-servico]/data
